In [1]:
import numpy as np

# Load EEG data (Assumed shape: (samples, time_steps, 4))
eeg_data = np.load("muse_eeg_data.npy", allow_pickle=True)

# Load labels (Assumed shape: (samples,))
eeg_labels = np.load("muse_eeg_labels.npy")

# Print shapes
print("EEG Data Shape:", eeg_data.shape)   # (samples, time_steps, 4)
print("Labels Shape:", eeg_labels.shape)   # (samples,)


EEG Data Shape: (50,)
Labels Shape: (50,)


In [2]:
eeg_data[0]

array([[-47.8515625 , -40.0390625 , -57.6171875 , -91.30859375],
       [-38.0859375 ,  -4.39453125, -23.92578125, -84.9609375 ],
       [-30.2734375 , -11.71875   , -22.4609375 , -70.3125    ],
       ...,
       [-50.78125   , -26.85546875, -30.2734375 , -85.9375    ],
       [-65.91796875, -21.97265625, -27.83203125, -85.44921875],
       [-61.03515625, -10.25390625, -18.06640625, -93.75      ]])

In [3]:
for i, sample in enumerate(eeg_data[:5]):  # Check first 5 samples
    print(f"Sample {i}: {type(sample)}, Shape: {np.array(sample).shape}")



Sample 0: <class 'numpy.ndarray'>, Shape: (2557, 4)
Sample 1: <class 'numpy.ndarray'>, Shape: (2568, 4)
Sample 2: <class 'numpy.ndarray'>, Shape: (2568, 4)
Sample 3: <class 'numpy.ndarray'>, Shape: (2568, 4)
Sample 4: <class 'numpy.ndarray'>, Shape: (2568, 4)


In [4]:
min_time_steps = min(sample.shape[0] for sample in eeg_data)  # Find shortest
eeg_data = np.array([sample[:min_time_steps] for sample in eeg_data])  # Truncate


In [5]:
for i, sample in enumerate(eeg_data[:5]):  # Check first 5 samples
    print(f"Sample {i}: {type(sample)}, Shape: {np.array(sample).shape}")

Sample 0: <class 'numpy.ndarray'>, Shape: (2556, 4)
Sample 1: <class 'numpy.ndarray'>, Shape: (2556, 4)
Sample 2: <class 'numpy.ndarray'>, Shape: (2556, 4)
Sample 3: <class 'numpy.ndarray'>, Shape: (2556, 4)
Sample 4: <class 'numpy.ndarray'>, Shape: (2556, 4)


In [6]:
eeg_data.shape

(50, 2556, 4)

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, BatchNormalization, LSTM, Dense, Dropout, Input

# Define input shape
input_shape = (2556, 4)  # (timesteps, features)
num_classes = 5  # 'dhp', 'sab', 'fbh', 'cfm', 'null'

# Model architecture
model = Sequential([
    Input(shape=input_shape),  # Define input explicitly
    Conv1D(filters=32, kernel_size=5, activation='relu', padding='same'),
    BatchNormalization(),
    Conv1D(filters=64, kernel_size=5, activation='relu', padding='same'),
    BatchNormalization(),
    LSTM(64, return_sequences=True),  # Keep time dimension
    LSTM(32),  # Reduce to vector
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')  # 5 output classes
])

# Compile model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Model summary
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 2556, 32)       │           672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 2556, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 2556, 64)       │        10,304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 2556, 64)       │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 2556, 64)       │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │           165 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 58,021 (226.64 KB)

 Trainable params: 57,829 (225.89 KB)

 Non-trainable params: 192 (768.00 B)

In [8]:
# Train the model
history = model.fit(eeg_data, eeg_labels, epochs=20, batch_size=8, validation_split=0.2)


Epoch 1/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 592ms/step - accuracy: 0.2309 - loss: 1.5857 - val_accuracy: 0.4000 - val_loss: 1.5148
Epoch 2/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 553ms/step - accuracy: 0.5111 - loss: 1.5009 - val_accuracy: 0.3000 - val_loss: 1.5193
Epoch 3/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 555ms/step - accuracy: 0.4017 - loss: 1.4483 - val_accuracy: 0.3000 - val_loss: 1.5378
Epoch 4/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 591ms/step - accuracy: 0.5965 - loss: 1.3616 - val_accuracy: 0.3000 - val_loss: 1.5810
Epoch 5/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 552ms/step - accuracy: 0.4330 - loss: 1.3538 - val_accuracy: 0.3000 - val_loss: 1.6026
Epoch 6/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 553ms/step - accuracy: 0.5323 - loss: 1.2706 - val_accuracy: 0.2000 - val_loss: 1.6251
Epoch 7/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 552ms/step - accuracy: 0.5597 - loss: 1.2198 - val_accuracy: 0.2000 - val_loss: 1.6490
Epoch 8/20
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 553ms/step - accuracy: 0.6236 - loss: 1.1557 - val_accuracy: 0.1000 - val_loss:

In [71]:
print(eeg_data.shape)  # Should be (50, 2556, 4)
print(eeg_labels.shape)  # Should be (50,)
print(np.unique(eeg_labels))  # Should contain values [0, 1, 2, 3, 4]


(50, 2556, 4)
(50,)
[0 1 2 3 4]


In [98]:
filename = "eeg_recording.txt"
eeg_file = np.loadtxt(filename, dtype=np.float32)

# Define target shape
target_samples = 2556
num_channels = 4

# Ensure it's a NumPy array
eeg_file = np.array(eeg_file, dtype=np.float32)

In [99]:
eeg_file.shape

(2557, 4)

In [100]:
eeg_file = eeg_file[:2556, :]  # Keep only the first 2556 rows
eeg_file.shape

(2556, 4)

In [101]:
eeg_file = eeg_file.reshape(1, 2556, 4)  # Add batch dimension
eeg_file.shape

(1, 2556, 4)

In [102]:
predictions = model.predict(eeg_file)
print(predictions[0])
# Get the predicted class
predicted_class = np.argmax(predictions, axis=1)[0]  # Returns the class index
print(predicted_class)
# Define class labels
top_2_indices = np.argsort(predictions[0])[-2:][::-1]

print(top_2_indices)

class_labels = ['relaxed', 'frustration', 'emergency trauma', 'sadness', 'null']

# Print predicted label
for i in top_2_indices:
    print(f"Predicted Class: {class_labels[i]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
[0.06331362 0.6065506  0.08134641 0.1631499  0.08563947]
1
[1 3]
Predicted Class: frustration
Predicted Class: sadness


In [106]:
top_2_indices

array([1, 3])

In [109]:
list(top_2_indices)

[1, 3]

In [105]:
model.save("brain_eeg_predict.h5")

In [103]:
import google.generativeai as genai

genai.configure(api_key="GEMINI API KEY")

top_emotions = []
confidence = []
for i in top_2_indices:
    print(f"Predicted Class: {class_labels[i]}")
    top_emotions.append(class_labels[i])
    confidence.append((predictions[0][i])*100)

print(top_emotions)
# Construct prompt request
prompt = (
    f"Generate a cinematic image prompt based on the following emotions:\n"
    f"- {top_emotions[0]} with confidence {confidence[0]}%"
    f"- {top_emotions[1]} with confidence {confidence[1]}%"
    "The image should depict a person"
    "The background should convey more emotion than the person, using lighting, scenery, and atmosphere to enhance the mood. The backgrond should be slightly exaggerated "
    "Ensure the scene is visually powerful and storytelling-driven, without any text in the image. make what they are thinking of related to the past like PTSD. make multiple people in the scene from 1 to 4"
    "If prompt is relaxed then make style very calm"
    "it doesnt always have to be sad depends on emotions and confidence. Depending on the confindence stress on that emotion"
)

# Generate response from Gemini
response = genai.GenerativeModel("gemini-1.5-pro-001").generate_content(prompt)
generated_prompt = response.text

print(generated_prompt)

Predicted Class: frustration
Predicted Class: sadness
['frustration', 'sadness']
## Cinematic Image Prompt:

**Scene:** A lone figure stands on a precipice overlooking a vast, fog-choked valley. The sun, a dull orange orb, is setting, casting long, distorted shadows across the landscape. The figure is silhouetted against the dying light, their features obscured. 

**Atmosphere:** The air hangs heavy with a palpable sense of melancholy and simmering frustration. The silence is broken only by the mournful cry of a distant bird and the low rumble of thunder in the distance, hinting at an approaching storm. 

**Background Details:** The valley below is a tapestry of decaying beauty. Twisted, skeletal trees claw at the sky, remnants of a once vibrant forest. Crumbling ruins of buildings peek through the fog, whispers of a forgotten past. A single, winding road disappears into the mist, leading towards the setting sun.

**Character:**  The figure's posture is one of defiant stillness, their 

In [104]:
import openai

openai.api_key = "OPENAI KEY"

response = openai.images.generate(
    model="dall-e-3",  # Use "dall-e-2" if you want a faster option
    prompt=f"{generated_prompt}",
    size="1024x1024",
    n=1
)

image_url = response.data[0].url
print(image_url)

https://oaidalleapiprodscus.blob.core.windows.net/private/org-TvBsULInBzYXjejn4vd3AiEy/user-kPhXGRO88DQJtMg5Vwl4hChs/img-GvUboxHwxtHfAoxa78B7VuCi.png?st=2025-03-01T15%3A58%3A56Z&se=2025-03-01T17%3A58%3A56Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-02-28T18%3A43%3A52Z&ske=2025-03-01T18%3A43%3A52Z&sks=b&skv=2024-08-04&sig=VeHkaYV%2B64dvnZ6ahfYk6kDPrI0k8xBnU4P27jFPpFU%3D
